# Generated by Django 2.2.5 on 2019-12-17 22:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Questionaires', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='questionaire',
            name='title',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
    ]
