# Generated by Django 2.2.5 on 2020-04-29 23:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Questionaires', '0003_auto_20200429_2322'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='order',
            field=models.IntegerField(default=1),
        ),
    ]
