# Generated by Django 2.2.5 on 2020-04-30 04:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Questionaires', '0004_question_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='questiontype',
            name='parent',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='Questionaires.QuestionType'),
        ),
    ]
