# Generated by Django 2.2.5 on 2020-04-30 04:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Questionaires', '0005_questiontype_parent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='questiontype',
            name='parent',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='Questionaires.QuestionType'),
        ),
    ]
