# Generated by Django 2.2.5 on 2020-04-30 06:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Questionaires', '0006_auto_20200430_0432'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='RadioChoices',
            new_name='RadioChoice',
        ),
    ]
