# Generated by Django 2.2.5 on 2020-05-02 05:43

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('Questionaires', '0007_auto_20200430_0614'),
    ]

    operations = [
        migrations.CreateModel(
            name='Response',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(default=django.utils.timezone.now)),
                ('questionaire', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Questionaires.Questionaire')),
            ],
        ),
        migrations.CreateModel(
            name='ResponseItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(blank=True, default='', max_length=1000)),
                ('checkbox', models.BooleanField(blank=True, null=True)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Questionaires.Question')),
                ('radio', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Questionaires.RadioChoice')),
                ('response', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Questionaires.Response')),
            ],
        ),
    ]
