# Generated by Django 2.2.5 on 2020-05-02 06:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Questionaires', '0008_response_responseitem'),
    ]

    operations = [
        migrations.AlterField(
            model_name='responseitem',
            name='text',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
    ]
